const activeUsers = [
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=78358",
    email: "#jjnte@enwrx.ss",
    id: 1,
    name: "Matthew",
    statusMessage: "reading book",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=43188",
    email: "#ghlryc@vcnvt.it",
    id: 2,
    name: "Carl",
    statusMessage: "watching TV",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=50770",
    email: "#mydcvo@lvegf.wz",
    id: 3,
    name: "Larry",
    statusMessage: "watching TV",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=39257",
    email: "#smisxxw@kuhzj.yy",
    id: 4,
    name: "Jack",
    statusMessage: "watching TV",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=35771",
    email: "#odulxtg@bjpwc.oo",
    id: 5,
    name: "Ty",
    statusMessage: "reading book",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=38274",
    email: "#alimxip@ktsdy.xw",
    id: 6,
    name: "Ben",
    statusMessage: "watching TV",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=62422",
    email: "#nddfwwd@ywmva.sg",
    id: 7,
    name: "Paul",
    statusMessage: "playing games",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=09382",
    email: "#ecuzcvaw@tlgto.ud",
    id: 8,
    name: "George",
    statusMessage: "working from home",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=22807",
    email: "#aouqhg@ayxna.oe",
    id: 9,
    name: "Monte",
    statusMessage: "playing games",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=52271",
    email: "#phnvxd@qrufl.wd",
    id: 10,
    name: "Tim",
    statusMessage: "playing games",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=53599",
    email: "#tzevegax@dgjet.sa",
    id: 11,
    name: "Victor",
    statusMessage: "playing games",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=02365",
    email: "#pzyyhd@wxwop.vk",
    id: 12,
    name: "Thomas",
    statusMessage: "teaching programming",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=76396",
    email: "#qixtwvg@emaow.av",
    id: 13,
    name: "Adam",
    statusMessage: "working from home",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=40542",
    email: "#mophr@qkjqq.yr",
    id: 14,
    name: "Peter",
    statusMessage: "playing games",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=80674",
    email: "#ocvwfgu@rnfyp.dm",
    id: 15,
    name: "Tim",
    statusMessage: "watching TV",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=78995",
    email: "#ferrnk@yateg.go",
    id: 16,
    name: "Thomas",
    statusMessage: "reading book",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=69457",
    email: "#nhvvab@fkvyj.pj",
    id: 17,
    name: "Paul",
    statusMessage: "working from home",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=85458",
    email: "#pjzwav@mcvgq.xi",
    id: 18,
    name: "Monte",
    statusMessage: "reading book",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=94550",
    email: "#yyspqhsa@sklyc.jd",
    id: 19,
    name: "Monte",
    statusMessage: "watching TV",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=73535",
    email: "#ydnfhpf@txyrd.wc",
    id: 20,
    name: "Paul",
    statusMessage: "exercising",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=97502",
    email: "#gtohjs@rdgex.qh",
    id: 21,
    name: "Hank",
    statusMessage: "working from home",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=60773",
    email: "#bxcfubr@ntwgw.ah",
    id: 22,
    name: "Nathan",
    statusMessage: "reading book",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=20159",
    email: "#gzvcokn@fyzze.vu",
    id: 23,
    name: "Ike",
    statusMessage: "playing games",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=91943",
    email: "#ysqombr@prhkp.yj",
    id: 24,
    name: "Walter",
    statusMessage: "working from home",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=31065",
    email: "#cjusjolk@eijxl.rm",
    id: 25,
    name: "Adam",
    statusMessage: "exercising",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=33457",
    email: "#sslkf@gtfkn.lr",
    id: 26,
    name: "Matthew",
    statusMessage: "exercising",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=56358",
    email: "#bthuul@mtsqe.yv",
    id: 27,
    name: "Thomas",
    statusMessage: "working from home",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=82670",
    email: "#qiwjkk@tuaww.ef",
    id: 28,
    name: "Dan",
    statusMessage: "watching TV",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=39024",
    email: "#idehlvp@gtjhl.wh",
    id: 29,
    name: "Edward",
    statusMessage: "reading book",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=40690",
    email: "#kqnytxbij@pqnyd.ew",
    id: 30,
    name: "Fred",
    statusMessage: "playing games",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=87882",
    email: "#tgajrh@xszpt.mi",
    id: 31,
    name: "Thomas",
    statusMessage: "exercising",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=95521",
    email: "#cqhbaft@gcgdm.uv",
    id: 32,
    name: "Nathan",
    statusMessage: "exercising",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=83499",
    email: "#ebcsd@emxhp.kn",
    id: 33,
    name: "John",
    statusMessage: "teaching programming",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=97489",
    email: "#zhphemi@mhrcs.gu",
    id: 34,
    name: "Larry",
    statusMessage: "teaching programming",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=80343",
    email: "#lpytif@zovmv.nd",
    id: 35,
    name: "Hank",
    statusMessage: "reading book",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=83949",
    email: "#oxsphhd@pairs.je",
    id: 36,
    name: "Frank",
    statusMessage: "exercising",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=60468",
    email: "#xgmgov@ydgeq.kb",
    id: 37,
    name: "Nathan",
    statusMessage: "working from home",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=50378",
    email: "#gdiip@pwjfu.ox",
    id: 38,
    name: "John",
    statusMessage: "playing games",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=93513",
    email: "#zptwwhak@vkltg.mf",
    id: 39,
    name: "Matthew",
    statusMessage: "exercising",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=48831",
    email: "#kyypp@dcvjz.tu",
    id: 40,
    name: "David",
    statusMessage: "watching TV",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=13589",
    email: "#nlrfxc@dopvi.pk",
    id: 41,
    name: "Alex",
    statusMessage: "watching TV",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=97448",
    email: "#wscmg@vcvth.lh",
    id: 42,
    name: "Frank",
    statusMessage: "working from home",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=52532",
    email: "#yzbzxo@qnlrf.st",
    id: 43,
    name: "Monte",
    statusMessage: "watching TV",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=76470",
    email: "#kvslkd@gfdbr.de",
    id: 44,
    name: "Joe",
    statusMessage: "reading book",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=80171",
    email: "#uckgpr@xllsk.rf",
    id: 45,
    name: "Joe",
    statusMessage: "teaching programming",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=84991",
    email: "#rwyhf@nfwql.ko",
    id: 46,
    name: "Aaron",
    statusMessage: "exercising",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=40995",
    email: "#pxjpqpy@yuqfd.ks",
    id: 47,
    name: "Edward",
    statusMessage: "reading book",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=25899",
    email: "#rfgcgfc@skotz.jj",
    id: 48,
    name: "Peter",
    statusMessage: "playing games",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=82246",
    email: "#leozw@dtshp.pk",
    id: 49,
    name: "Thomas",
    statusMessage: "watching TV",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=41672",
    email: "#xawireq@nqzdz.he",
    id: 50,
    name: "David",
    statusMessage: "watching TV",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=35494",
    email: "#cjjduh@juwvv.xt",
    id: 51,
    name: "Monte",
    statusMessage: "playing games",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=60787",
    email: "#dbyeapa@gbjka.vq",
    id: 52,
    name: "John",
    statusMessage: "working from home",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=49294",
    email: "#wpttzv@ozxft.te",
    id: 53,
    name: "Thomas",
    statusMessage: "teaching programming",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=69630",
    email: "#dzxys@vjkjv.vz",
    id: 54,
    name: "Tim",
    statusMessage: "teaching programming",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=17447",
    email: "#qftvt@ceqac.fp",
    id: 55,
    name: "Joe",
    statusMessage: "working from home",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=27434",
    email: "#fyzkbettq@qxtii.nq",
    id: 56,
    name: "Peter",
    statusMessage: "playing games",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=81090",
    email: "#hbpohz@degjm.ek",
    id: 57,
    name: "Roger",
    statusMessage: "exercising",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=94237",
    email: "#dwjejc@dbiij.ry",
    id: 58,
    name: "Ike",
    statusMessage: "exercising",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=68755",
    email: "#aebwio@txoay.pi",
    id: 59,
    name: "Otto",
    statusMessage: "watching TV",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=44355",
    email: "#zlrjan@rwuqb.fo",
    id: 60,
    name: "Ben",
    statusMessage: "reading book",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=00771",
    email: "#oijkhmm@tssnr.va",
    id: 61,
    name: "Aaron",
    statusMessage: "reading book",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=91735",
    email: "#vghio@bbghj.td",
    id: 62,
    name: "Thomas",
    statusMessage: "watching TV",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=63511",
    email: "#rlitfvt@hiotj.fh",
    id: 63,
    name: "Otto",
    statusMessage: "working from home",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=51539",
    email: "#cveia@sfmos.fz",
    id: 64,
    name: "Paul",
    statusMessage: "teaching programming",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=53887",
    email: "#fbgbky@pxudb.dv",
    id: 65,
    name: "Nathan",
    statusMessage: "reading book",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=61049",
    email: "#qqxxe@hkbcl.xk",
    id: 66,
    name: "Hal",
    statusMessage: "working from home",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=43132",
    email: "#vlovcph@ootnb.ey",
    id: 67,
    name: "Otto",
    statusMessage: "exercising",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=05795",
    email: "#vuovmnx@cmexj.lv",
    id: 68,
    name: "Hank",
    statusMessage: "teaching programming",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=13992",
    email: "#wirzq@merzz.hv",
    id: 69,
    name: "Peter",
    statusMessage: "exercising",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=30071",
    email: "#kxtdykq@shitw.dg",
    id: 70,
    name: "Carl",
    statusMessage: "playing games",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=19711",
    email: "#farqkztr@yeijt.la",
    id: 71,
    name: "Tim",
    statusMessage: "exercising",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=12630",
    email: "#khmoes@evmly.sf",
    id: 72,
    name: "Edward",
    statusMessage: "exercising",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=57666",
    email: "#sedqz@uatgo.cw",
    id: 73,
    name: "Paul",
    statusMessage: "exercising",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=25790",
    email: "#ryrtpelq@iwiiq.sf",
    id: 74,
    name: "Tim",
    statusMessage: "teaching programming",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=94475",
    email: "#tixwhtf@bbzqi.bz",
    id: 75,
    name: "Peter",
    statusMessage: "watching TV",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=29185",
    email: "#rgbmomk@jyyxi.vb",
    id: 76,
    name: "Mark",
    statusMessage: "working from home",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=03852",
    email: "#iwffypwv@kzali.wh",
    id: 77,
    name: "Frank",
    statusMessage: "working from home",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=45649",
    email: "#jvsrwhq@xirhk.if",
    id: 78,
    name: "Steve",
    statusMessage: "playing games",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=81207",
    email: "#spmvgcu@dhmfb.db",
    id: 79,
    name: "Peter",
    statusMessage: "working from home",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=39791",
    email: "#emwoo@pzmxn.tl",
    id: 80,
    name: "David",
    statusMessage: "playing games",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=27697",
    email: "#axystuz@egxvx.an",
    id: 81,
    name: "Hank",
    statusMessage: "reading book",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=35570",
    email: "#qdzqmodh@krxuu.ly",
    id: 82,
    name: "Edward",
    statusMessage: "exercising",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=95717",
    email: "#duwzbwk@zzesl.jp",
    id: 83,
    name: "Otto",
    statusMessage: "exercising",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=35422",
    email: "#aahgyf@hgsdc.ma",
    id: 84,
    name: "Jack",
    statusMessage: "playing games",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=53606",
    email: "#dxkkau@ggevb.gx",
    id: 85,
    name: "Adam",
    statusMessage: "working from home",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=54270",
    email: "#hxuad@bmhwh.uu",
    id: 86,
    name: "Nathan",
    statusMessage: "watching TV",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=48454",
    email: "#xlmohl@oskvw.dp",
    id: 87,
    name: "David",
    statusMessage: "watching TV",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=96733",
    email: "#kydhgdl@gxabs.xl",
    id: 88,
    name: "Thomas",
    statusMessage: "playing games",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=02357",
    email: "#poxyyjr@whbbb.lf",
    id: 89,
    name: "Roger",
    statusMessage: "teaching programming",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=87434",
    email: "#kdpgciex@ikrbs.nb",
    id: 90,
    name: "Dan",
    statusMessage: "exercising",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=07035",
    email: "#aoysylla@smrxw.ju",
    id: 91,
    name: "Mark",
    statusMessage: "reading book",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=20003",
    email: "#rmthls@bztdp.mr",
    id: 92,
    name: "Dan",
    statusMessage: "watching TV",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=26833",
    email: "#cusuns@ynpjt.jt",
    id: 93,
    name: "Fred",
    statusMessage: "reading book",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=76797",
    email: "#hepjehi@pxwsk.wb",
    id: 94,
    name: "Aaron",
    statusMessage: "teaching programming",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=06272",
    email: "#ztxdu@jqkyz.uz",
    id: 95,
    name: "Carl",
    statusMessage: "teaching programming",
  },
  {
    activity: "offline",
    avatarUrl: "https://i.pravatar.cc/150?u=02745",
    email: "#peppj@jibew.zp",
    id: 96,
    name: "Larry",
    statusMessage: "watching TV",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=30258",
    email: "#dwibtn@tlfag.ln",
    id: 97,
    name: "Victor",
    statusMessage: "teaching programming",
  },
  {
    activity: "online",
    avatarUrl: "https://i.pravatar.cc/150?u=59085",
    email: "#knjqja@ccyah.gy",
    id: 98,
    name: "Roger",
    statusMessage: "playing games",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=20859",
    email: "#mgqnffj@guxua.vn",
    id: 99,
    name: "David",
    statusMessage: "exercising",
  },
  {
    activity: "streaming",
    avatarUrl: "https://i.pravatar.cc/150?u=00735",
    email: "#hdkmkhws@myato.ln",
    id: 100,
    name: "George",
    statusMessage: "reading book",
  },
];
